version: '3.8'

services:

  postgres:
    image: postgres
    restart: always
    ports: 
      - "5432:5432"
    environment:
      - DATABASE_HOST=172.24.240.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=PAPELARIA

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "zzpior@hotmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"  
    depends_on:
      - postgres
