----------------------------------------------------------------------------
CREATE DATABASE PAPELARIA;
----------------------------------------------------------------------------

CREATE TABLE CATEGORIA(
ID   BIGSERIAL NOT NULL,--BIG SERIAL JÁ CRIA A SEQUENCIA AUTOMATICAMENTE
NOME VARCHAR(30) NOT NULL 
);

  CREATE TABLE PRODUTO
 (
	ID BIGSERIAL NOT NULL , --BIG SERIAL JÁ CRIA A SEQUENCIA AUTOMATICAMENTE
	COD_BARRAS VARCHAR(13) NOT NULL , 
	DESCRICAO VARCHAR(50) NOT NULL , 
	QUANTIDADE NUMERIC  NOT NULL , 
	PRECO NUMERIC(18,2) , 
	PRECO_COM_DESCONTO NUMERIC(18,2) , 
    DESCONTO_PERCENTUAL NUMERIC(18,2) ,
    NOME VARCHAR(30) NOT NULL , 
	CATEGORIA_ID bigint  , 
	DETALHE VARCHAR(50) , 
	 PRIMARY KEY (ID),
	 CONSTRAINT FK_CATEGORIA 
    FOREIGN KEY (CATEGORIA_ID)
    REFERENCES CATEGORIA(ID)
   );
-------------------------------------------------------------------
----NSERTS  CATEGORIA DE PRODUTOS
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------   
   INSERT INTO CATEGORIA 
   (ID,NOME)
   VALUES
   (nextval('categoria_id_seq'),'MATERIAL ESCOLAR');
   
    INSERT INTO CATEGORIA 
   (ID,NOME)
   VALUES
   (nextval('categoria_id_seq'),'MATERIAL ESCRITORIO');
   
   INSERT INTO CATEGORIA 
   (ID,NOME)
   VALUES
   (nextval('categoria_id_seq'),'ELETRONICOS');
   
    INSERT INTO CATEGORIA 
   (ID,NOME)
   VALUES
   (nextval('categoria_id_seq'),'OUTROS');
   
    INSERT INTO CATEGORIA 
   (ID,NOME)
   VALUES
   (nextval('categoria_id_seq'),'CARTÕES PRÉ-PAGOS');
   
   INSERT INTO CATEGORIA 
   (ID,NOME)
   VALUES
   (nextval('categoria_id_seq'),'VALE-PRESENTES');
   
   INSERT INTO CATEGORIA 
   (ID,NOME)
   VALUES
   (nextval('categoria_id_seq'),'SOUVENIERS');
   
   INSERT INTO CATEGORIA 
   (ID,NOME)
   VALUES
   (nextval('categoria_id_seq'),'CD/DVD');
   
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------   
----NSERTS PRODUTOS
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
INSERT INTO PRODUTO 
(ID,COD_BARRAS,DESCRICAO,QUANTIDADE,PRECO,PRECO_COM_DESCONTO,DESCONTO_PERCENTUAL,NOME,CATEGORIA_ID,DETALHE)
VALUES
(nextval('produto_id_seq'),'0000000000','DESCRICAO PRODUTO A',000,00.00,00.00,00.00,'NOME  PRODUTO A',(SELECT C.ID FROM CATEGORIA C WHERE C.NOME='MATERIAL ESCRITORIO' ),'DETALHE  PRODUTO A');

INSERT INTO PRODUTO 
(ID,COD_BARRAS,DESCRICAO,QUANTIDADE,PRECO,PRECO_COM_DESCONTO,DESCONTO_PERCENTUAL,NOME,CATEGORIA_ID,DETALHE)
VALUES
(nextval('produto_id_seq'),'1111111111','DESCRICAO PRODUTO B',000,00.00,00.00,00.00,'NOME  PRODUTO B',(SELECT C.ID FROM CATEGORIA C WHERE C.NOME='MATERIAL ESCOLAR' ),'DETALHE  PRODUTO B');

INSERT INTO PRODUTO 
(ID,COD_BARRAS,DESCRICAO,QUANTIDADE,PRECO,PRECO_COM_DESCONTO,DESCONTO_PERCENTUAL,NOME,CATEGORIA_ID,DETALHE)
VALUES
(nextval('produto_id_seq'),'2222222222','DESCRICAO PRODUTO C',000,00.00,00.00,00.00,'NOME  PRODUTO C',(SELECT C.ID FROM CATEGORIA C WHERE C.NOME='ELETRONICOS' ),'DETALHE  PRODUTO C');

INSERT INTO PRODUTO 
(ID,COD_BARRAS,DESCRICAO,QUANTIDADE,PRECO,PRECO_COM_DESCONTO,DESCONTO_PERCENTUAL,NOME,CATEGORIA_ID,DETALHE)
VALUES
(nextval('produto_id_seq'),'3333333333','DESCRICAO PRODUTO D',000,00.00,00.00,00.00,'NOME  PRODUTO D',(SELECT C.ID FROM CATEGORIA C WHERE C.NOME='CD/DVD' ),'DETALHE  PRODUTO D');

INSERT INTO PRODUTO 
(ID,COD_BARRAS,DESCRICAO,QUANTIDADE,PRECO,PRECO_COM_DESCONTO,DESCONTO_PERCENTUAL,NOME,CATEGORIA_ID,DETALHE)
VALUES
(nextval('produto_id_seq'),'4444444444','DESCRICAO PRODUTO E',000,00.00,00.00,00.00,'NOME  PRODUTO E',(SELECT C.ID FROM CATEGORIA C WHERE C.NOME='SOUVENIERS' ),'DETALHE  PRODUTO E');

INSERT INTO PRODUTO 
(ID,COD_BARRAS,DESCRICAO,QUANTIDADE,PRECO,PRECO_COM_DESCONTO,DESCONTO_PERCENTUAL,NOME,CATEGORIA_ID,DETALHE)
VALUES
(nextval('produto_id_seq'),'5555555555','DESCRICAO PRODUTO F',000,00.00,00.00,00.00,'NOME  PRODUTO F',(SELECT C.ID FROM CATEGORIA C WHERE C.NOME='MATERIAL ESCRITORIO' ),'DETALHE  PRODUTO F');

INSERT INTO PRODUTO 
(ID,COD_BARRAS,DESCRICAO,QUANTIDADE,PRECO,PRECO_COM_DESCONTO,DESCONTO_PERCENTUAL,NOME,CATEGORIA_ID,DETALHE)
VALUES
(nextval('produto_id_seq'),'6666666666','DESCRICAO PRODUTO G',000,00.00,00.00,00.00,'NOME  PRODUTO G',(SELECT C.ID FROM CATEGORIA C WHERE C.NOME='CARTÕES PRÉ-PAGOS' ),'DETALHE  PRODUTO G');

INSERT INTO PRODUTO 
(ID,COD_BARRAS,DESCRICAO,QUANTIDADE,PRECO,PRECO_COM_DESCONTO,DESCONTO_PERCENTUAL,NOME,CATEGORIA_ID,DETALHE)
VALUES
(nextval('produto_id_seq'),'7777777777','DESCRICAO PRODUTO H',000,00.00,00.00,00.00,'NOME  PRODUTO H',(SELECT C.ID FROM CATEGORIA C WHERE C.NOME='ELETRONICOS' ),'DETALHE  PRODUTO H');

INSERT INTO PRODUTO 
(ID,COD_BARRAS,DESCRICAO,QUANTIDADE,PRECO,PRECO_COM_DESCONTO,DESCONTO_PERCENTUAL,NOME,CATEGORIA_ID,DETALHE)
VALUES
(nextval('produto_id_seq'),'8888888888','DESCRICAO PRODUTO I',000,00.00,00.00,00.00,'NOME  PRODUTO I',(SELECT C.ID FROM CATEGORIA C WHERE C.NOME='CD/DVD' ),'DETALHE  PRODUTO I');

INSERT INTO PRODUTO 
(ID,COD_BARRAS,DESCRICAO,QUANTIDADE,PRECO,PRECO_COM_DESCONTO,DESCONTO_PERCENTUAL,NOME,CATEGORIA_ID,DETALHE)
VALUES
(nextval('produto_id_seq'),'9999999999','DESCRICAO PRODUTO J',000,00.00,00.00,00.00,'NOME  PRODUTO J',(SELECT C.ID FROM CATEGORIA C WHERE C.NOME='OUTROS' ),'DETALHE  PRODUTO J');


-----------------------------------------------------------------
--verificando a inserção
SELECT * FROM PRODUTO PRO, CATEGORIA CAT
WHERE CAT.ID=PRO.CATEGORIA_ID